// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.createAccountStmt, err = db.PrepareContext(ctx, createAccount); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAccount: %w", err)
	}
	if q.createDepositStmt, err = db.PrepareContext(ctx, createDeposit); err != nil {
		return nil, fmt.Errorf("error preparing query CreateDeposit: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.getAccountByUserAndTypeStmt, err = db.PrepareContext(ctx, getAccountByUserAndType); err != nil {
		return nil, fmt.Errorf("error preparing query GetAccountByUserAndType: %w", err)
	}
	if q.getAccountsByUserIDStmt, err = db.PrepareContext(ctx, getAccountsByUserID); err != nil {
		return nil, fmt.Errorf("error preparing query GetAccountsByUserID: %w", err)
	}
	if q.getTransactionByIDStmt, err = db.PrepareContext(ctx, getTransactionByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetTransactionByID: %w", err)
	}
	if q.getTransactionsByAccountIDStmt, err = db.PrepareContext(ctx, getTransactionsByAccountID); err != nil {
		return nil, fmt.Errorf("error preparing query GetTransactionsByAccountID: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.getUserByIDStmt, err = db.PrepareContext(ctx, getUserByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByID: %w", err)
	}
	if q.getUserByUsernameStmt, err = db.PrepareContext(ctx, getUserByUsername); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByUsername: %w", err)
	}
	if q.updateAccountBalanceStmt, err = db.PrepareContext(ctx, updateAccountBalance); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateAccountBalance: %w", err)
	}
	if q.updateTransactionStatusStmt, err = db.PrepareContext(ctx, updateTransactionStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateTransactionStatus: %w", err)
	}
	if q.updateUserVerificationStmt, err = db.PrepareContext(ctx, updateUserVerification); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserVerification: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.createAccountStmt != nil {
		if cerr := q.createAccountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAccountStmt: %w", cerr)
		}
	}
	if q.createDepositStmt != nil {
		if cerr := q.createDepositStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createDepositStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.getAccountByUserAndTypeStmt != nil {
		if cerr := q.getAccountByUserAndTypeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAccountByUserAndTypeStmt: %w", cerr)
		}
	}
	if q.getAccountsByUserIDStmt != nil {
		if cerr := q.getAccountsByUserIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAccountsByUserIDStmt: %w", cerr)
		}
	}
	if q.getTransactionByIDStmt != nil {
		if cerr := q.getTransactionByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTransactionByIDStmt: %w", cerr)
		}
	}
	if q.getTransactionsByAccountIDStmt != nil {
		if cerr := q.getTransactionsByAccountIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTransactionsByAccountIDStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.getUserByIDStmt != nil {
		if cerr := q.getUserByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByIDStmt: %w", cerr)
		}
	}
	if q.getUserByUsernameStmt != nil {
		if cerr := q.getUserByUsernameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByUsernameStmt: %w", cerr)
		}
	}
	if q.updateAccountBalanceStmt != nil {
		if cerr := q.updateAccountBalanceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateAccountBalanceStmt: %w", cerr)
		}
	}
	if q.updateTransactionStatusStmt != nil {
		if cerr := q.updateTransactionStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateTransactionStatusStmt: %w", cerr)
		}
	}
	if q.updateUserVerificationStmt != nil {
		if cerr := q.updateUserVerificationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserVerificationStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                             DBTX
	tx                             *sql.Tx
	createAccountStmt              *sql.Stmt
	createDepositStmt              *sql.Stmt
	createUserStmt                 *sql.Stmt
	getAccountByUserAndTypeStmt    *sql.Stmt
	getAccountsByUserIDStmt        *sql.Stmt
	getTransactionByIDStmt         *sql.Stmt
	getTransactionsByAccountIDStmt *sql.Stmt
	getUserByEmailStmt             *sql.Stmt
	getUserByIDStmt                *sql.Stmt
	getUserByUsernameStmt          *sql.Stmt
	updateAccountBalanceStmt       *sql.Stmt
	updateTransactionStatusStmt    *sql.Stmt
	updateUserVerificationStmt     *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                             tx,
		tx:                             tx,
		createAccountStmt:              q.createAccountStmt,
		createDepositStmt:              q.createDepositStmt,
		createUserStmt:                 q.createUserStmt,
		getAccountByUserAndTypeStmt:    q.getAccountByUserAndTypeStmt,
		getAccountsByUserIDStmt:        q.getAccountsByUserIDStmt,
		getTransactionByIDStmt:         q.getTransactionByIDStmt,
		getTransactionsByAccountIDStmt: q.getTransactionsByAccountIDStmt,
		getUserByEmailStmt:             q.getUserByEmailStmt,
		getUserByIDStmt:                q.getUserByIDStmt,
		getUserByUsernameStmt:          q.getUserByUsernameStmt,
		updateAccountBalanceStmt:       q.updateAccountBalanceStmt,
		updateTransactionStatusStmt:    q.updateTransactionStatusStmt,
		updateUserVerificationStmt:     q.updateUserVerificationStmt,
	}
}
