// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Account struct {
	ID               uuid.UUID      `json:"id"`
	UserID           uuid.UUID      `json:"user_id"`
	AccountType      string         `json:"account_type"`
	Balance          sql.NullString `json:"balance"`
	AvailableBalance sql.NullString `json:"available_balance"`
	LockedBalance    sql.NullString `json:"locked_balance"`
	Currency         string         `json:"currency"`
	IsActive         sql.NullBool   `json:"is_active"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
	CurrencyID       uuid.NullUUID  `json:"currency_id"`
}

type ApiKey struct {
	ID          uuid.UUID    `json:"id"`
	UserID      uuid.UUID    `json:"user_id"`
	Name        string       `json:"name"`
	KeyHash     string       `json:"key_hash"`
	SecretHash  string       `json:"secret_hash"`
	Permissions []string     `json:"permissions"`
	IsActive    sql.NullBool `json:"is_active"`
	LastUsedAt  sql.NullTime `json:"last_used_at"`
	ExpiresAt   sql.NullTime `json:"expires_at"`
	CreatedAt   sql.NullTime `json:"created_at"`
}

type AuditLog struct {
	ID           uuid.UUID             `json:"id"`
	UserID       uuid.NullUUID         `json:"user_id"`
	Action       string                `json:"action"`
	ResourceType sql.NullString        `json:"resource_type"`
	ResourceID   uuid.NullUUID         `json:"resource_id"`
	IpAddress    sql.NullString        `json:"ip_address"`
	UserAgent    sql.NullString        `json:"user_agent"`
	Details      pqtype.NullRawMessage `json:"details"`
	CreatedAt    sql.NullTime          `json:"created_at"`
}

type Currency struct {
	ID                  uuid.UUID      `json:"id"`
	Code                string         `json:"code"`
	Name                string         `json:"name"`
	Type                string         `json:"type"`
	Decimals            int32          `json:"decimals"`
	MinWithdrawal       string         `json:"min_withdrawal"`
	MaxWithdrawal       sql.NullString `json:"max_withdrawal"`
	WithdrawalFee       sql.NullString `json:"withdrawal_fee"`
	IsDepositEnabled    sql.NullBool   `json:"is_deposit_enabled"`
	IsWithdrawalEnabled sql.NullBool   `json:"is_withdrawal_enabled"`
	IsTradingEnabled    sql.NullBool   `json:"is_trading_enabled"`
	IsActive            sql.NullBool   `json:"is_active"`
	CreatedAt           sql.NullTime   `json:"created_at"`
	UpdatedAt           sql.NullTime   `json:"updated_at"`
}

type FeeTier struct {
	ID           uuid.UUID      `json:"id"`
	TierName     string         `json:"tier_name"`
	Min30dVolume string         `json:"min_30d_volume"`
	Max30dVolume sql.NullString `json:"max_30d_volume"`
	MakerFeeRate string         `json:"maker_fee_rate"`
	TakerFeeRate string         `json:"taker_fee_rate"`
	Priority     int32          `json:"priority"`
	IsActive     sql.NullBool   `json:"is_active"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

type Order struct {
	ID                uuid.UUID      `json:"id"`
	UserID            uuid.UUID      `json:"user_id"`
	AccountID         uuid.UUID      `json:"account_id"`
	TradingPairID     uuid.UUID      `json:"trading_pair_id"`
	Symbol            string         `json:"symbol"`
	OrderType         string         `json:"order_type"`
	Side              string         `json:"side"`
	Price             sql.NullString `json:"price"`
	Quantity          string         `json:"quantity"`
	FilledQuantity    sql.NullString `json:"filled_quantity"`
	RemainingQuantity string         `json:"remaining_quantity"`
	Status            string         `json:"status"`
	TimeInForce       sql.NullString `json:"time_in_force"`
	StopPrice         sql.NullString `json:"stop_price"`
	ClientOrderID     sql.NullString `json:"client_order_id"`
	CreatedAt         sql.NullTime   `json:"created_at"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
	ExpiresAt         sql.NullTime   `json:"expires_at"`
}

type OrderMetric struct {
	ID              uuid.UUID      `json:"id"`
	Symbol          string         `json:"symbol"`
	MetricDate      time.Time      `json:"metric_date"`
	TotalOrders     sql.NullInt64  `json:"total_orders"`
	TotalTrades     sql.NullInt64  `json:"total_trades"`
	TotalVolume     sql.NullString `json:"total_volume"`
	AvgFillTimeMs   sql.NullInt32  `json:"avg_fill_time_ms"`
	MaxFillTimeMs   sql.NullInt32  `json:"max_fill_time_ms"`
	OrdersPerSecond sql.NullString `json:"orders_per_second"`
	CreatedAt       sql.NullTime   `json:"created_at"`
}

type OrderbookSnapshot struct {
	ID            uuid.UUID       `json:"id"`
	TradingPairID uuid.UUID       `json:"trading_pair_id"`
	Symbol        string          `json:"symbol"`
	SnapshotData  json.RawMessage `json:"snapshot_data"`
	OrderCount    int32           `json:"order_count"`
	BidCount      int32           `json:"bid_count"`
	AskCount      int32           `json:"ask_count"`
	BestBid       sql.NullString  `json:"best_bid"`
	BestAsk       sql.NullString  `json:"best_ask"`
	CreatedAt     sql.NullTime    `json:"created_at"`
}

type Session struct {
	ID               uuid.UUID      `json:"id"`
	UserID           uuid.UUID      `json:"user_id"`
	TokenHash        string         `json:"token_hash"`
	RefreshTokenHash sql.NullString `json:"refresh_token_hash"`
	IpAddress        sql.NullString `json:"ip_address"`
	UserAgent        sql.NullString `json:"user_agent"`
	ExpiresAt        time.Time      `json:"expires_at"`
	CreatedAt        sql.NullTime   `json:"created_at"`
	LastActivity     sql.NullTime   `json:"last_activity"`
}

type Trade struct {
	ID            uuid.UUID      `json:"id"`
	OrderID       uuid.UUID      `json:"order_id"`
	TradingPairID uuid.UUID      `json:"trading_pair_id"`
	Symbol        string         `json:"symbol"`
	BuyerID       uuid.UUID      `json:"buyer_id"`
	SellerID      uuid.UUID      `json:"seller_id"`
	BuyerOrderID  uuid.UUID      `json:"buyer_order_id"`
	SellerOrderID uuid.UUID      `json:"seller_order_id"`
	Price         string         `json:"price"`
	Quantity      string         `json:"quantity"`
	Total         string         `json:"total"`
	Fee           sql.NullString `json:"fee"`
	FeeCurrency   sql.NullString `json:"fee_currency"`
	TradeSide     string         `json:"trade_side"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	MakerOrderID  uuid.NullUUID  `json:"maker_order_id"`
	TakerOrderID  uuid.NullUUID  `json:"taker_order_id"`
	MakerFee      sql.NullString `json:"maker_fee"`
	TakerFee      sql.NullString `json:"taker_fee"`
	MakerFeeRate  sql.NullString `json:"maker_fee_rate"`
	TakerFeeRate  sql.NullString `json:"taker_fee_rate"`
}

type TradingPair struct {
	ID                uuid.UUID     `json:"id"`
	Symbol            string        `json:"symbol"`
	BaseCurrency      string        `json:"base_currency"`
	QuoteCurrency     string        `json:"quote_currency"`
	MinOrderSize      string        `json:"min_order_size"`
	MaxOrderSize      string        `json:"max_order_size"`
	PricePrecision    int32         `json:"price_precision"`
	QuantityPrecision int32         `json:"quantity_precision"`
	IsActive          sql.NullBool  `json:"is_active"`
	CreatedAt         sql.NullTime  `json:"created_at"`
	UpdatedAt         sql.NullTime  `json:"updated_at"`
	BaseCurrencyID    uuid.NullUUID `json:"base_currency_id"`
	QuoteCurrencyID   uuid.NullUUID `json:"quote_currency_id"`
}

type Transaction struct {
	ID              uuid.UUID      `json:"id"`
	AccountID       uuid.UUID      `json:"account_id"`
	TransactionType string         `json:"transaction_type"`
	Amount          string         `json:"amount"`
	Currency        string         `json:"currency"`
	BalanceBefore   string         `json:"balance_before"`
	BalanceAfter    string         `json:"balance_after"`
	Status          string         `json:"status"`
	ReferenceID     uuid.NullUUID  `json:"reference_id"`
	ReferenceType   sql.NullString `json:"reference_type"`
	Description     sql.NullString `json:"description"`
	CreatedAt       sql.NullTime   `json:"created_at"`
}

type User struct {
	ID           uuid.UUID      `json:"id"`
	Username     string         `json:"username"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	FirstName    sql.NullString `json:"first_name"`
	LastName     sql.NullString `json:"last_name"`
	IsActive     sql.NullBool   `json:"is_active"`
	IsVerified   sql.NullBool   `json:"is_verified"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type UserFeeTier struct {
	ID               uuid.UUID      `json:"id"`
	UserID           uuid.UUID      `json:"user_id"`
	FeeTierID        uuid.UUID      `json:"fee_tier_id"`
	Volume30d        sql.NullString `json:"volume_30d"`
	LastCalculatedAt sql.NullTime   `json:"last_calculated_at"`
	ValidUntil       sql.NullTime   `json:"valid_until"`
	CreatedAt        sql.NullTime   `json:"created_at"`
}
