// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    user_id,
    account_type,
    balance,
    available_balance,
    locked_balance,
    currency
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, account_type, balance, available_balance, locked_balance, currency, is_active, created_at, updated_at, currency_id
`

type CreateAccountParams struct {
	UserID           uuid.UUID      `json:"user_id"`
	AccountType      string         `json:"account_type"`
	Balance          sql.NullString `json:"balance"`
	AvailableBalance sql.NullString `json:"available_balance"`
	LockedBalance    sql.NullString `json:"locked_balance"`
	Currency         string         `json:"currency"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.queryRow(ctx, q.createAccountStmt, createAccount,
		arg.UserID,
		arg.AccountType,
		arg.Balance,
		arg.AvailableBalance,
		arg.LockedBalance,
		arg.Currency,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountType,
		&i.Balance,
		&i.AvailableBalance,
		&i.LockedBalance,
		&i.Currency,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrencyID,
	)
	return i, err
}

const createDeposit = `-- name: CreateDeposit :one
INSERT INTO transactions (
    account_id,
    transaction_type,
    amount,
    currency,
    balance_before,
    balance_after,
    status,
    reference_id
)
VALUES ($1, 'deposit', $2, $3, $4, $5, $6, $7)
RETURNING id, account_id, transaction_type, amount, currency, balance_before, balance_after, status, reference_id, reference_type, description, created_at
`

type CreateDepositParams struct {
	AccountID     uuid.UUID     `json:"account_id"`
	Amount        string        `json:"amount"`
	Currency      string        `json:"currency"`
	BalanceBefore string        `json:"balance_before"`
	BalanceAfter  string        `json:"balance_after"`
	Status        string        `json:"status"`
	ReferenceID   uuid.NullUUID `json:"reference_id"`
}

func (q *Queries) CreateDeposit(ctx context.Context, arg CreateDepositParams) (Transaction, error) {
	row := q.queryRow(ctx, q.createDepositStmt, createDeposit,
		arg.AccountID,
		arg.Amount,
		arg.Currency,
		arg.BalanceBefore,
		arg.BalanceAfter,
		arg.Status,
		arg.ReferenceID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TransactionType,
		&i.Amount,
		&i.Currency,
		&i.BalanceBefore,
		&i.BalanceAfter,
		&i.Status,
		&i.ReferenceID,
		&i.ReferenceType,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username, 
    email, 
    password_hash, 
    first_name, 
    last_name
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, email, password_hash, first_name, last_name, is_active, is_verified, created_at, updated_at
`

type CreateUserParams struct {
	Username     string         `json:"username"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"password_hash"`
	FirstName    sql.NullString `json:"first_name"`
	LastName     sql.NullString `json:"last_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByUserAndType = `-- name: GetAccountByUserAndType :one
SELECT id, user_id, account_type, balance, available_balance, locked_balance, currency, is_active, created_at, updated_at, currency_id FROM accounts
WHERE user_id = $1 
  AND account_type = $2
  AND currency = $3
LIMIT 1
`

type GetAccountByUserAndTypeParams struct {
	UserID      uuid.UUID `json:"user_id"`
	AccountType string    `json:"account_type"`
	Currency    string    `json:"currency"`
}

func (q *Queries) GetAccountByUserAndType(ctx context.Context, arg GetAccountByUserAndTypeParams) (Account, error) {
	row := q.queryRow(ctx, q.getAccountByUserAndTypeStmt, getAccountByUserAndType, arg.UserID, arg.AccountType, arg.Currency)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountType,
		&i.Balance,
		&i.AvailableBalance,
		&i.LockedBalance,
		&i.Currency,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrencyID,
	)
	return i, err
}

const getAccountsByUserID = `-- name: GetAccountsByUserID :many
SELECT id, user_id, account_type, balance, available_balance, locked_balance, currency, is_active, created_at, updated_at, currency_id FROM accounts
WHERE user_id = $1
  AND is_active = true
ORDER BY created_at DESC
`

func (q *Queries) GetAccountsByUserID(ctx context.Context, userID uuid.UUID) ([]Account, error) {
	rows, err := q.query(ctx, q.getAccountsByUserIDStmt, getAccountsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountType,
			&i.Balance,
			&i.AvailableBalance,
			&i.LockedBalance,
			&i.Currency,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrencyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, account_id, transaction_type, amount, currency, balance_before, balance_after, status, reference_id, reference_type, description, created_at FROM transactions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.queryRow(ctx, q.getTransactionByIDStmt, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TransactionType,
		&i.Amount,
		&i.Currency,
		&i.BalanceBefore,
		&i.BalanceAfter,
		&i.Status,
		&i.ReferenceID,
		&i.ReferenceType,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionsByAccountID = `-- name: GetTransactionsByAccountID :many
SELECT id, account_id, transaction_type, amount, currency, balance_before, balance_after, status, reference_id, reference_type, description, created_at FROM transactions
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetTransactionsByAccountIDParams struct {
	AccountID uuid.UUID `json:"account_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) GetTransactionsByAccountID(ctx context.Context, arg GetTransactionsByAccountIDParams) ([]Transaction, error) {
	rows, err := q.query(ctx, q.getTransactionsByAccountIDStmt, getTransactionsByAccountID, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TransactionType,
			&i.Amount,
			&i.Currency,
			&i.BalanceBefore,
			&i.BalanceAfter,
			&i.Status,
			&i.ReferenceID,
			&i.ReferenceType,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, first_name, last_name, is_active, is_verified, created_at, updated_at FROM users
WHERE email = $1 
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.queryRow(ctx, q.getUserByEmailStmt, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, first_name, last_name, is_active, is_verified, created_at, updated_at FROM users
WHERE id = $1 
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.queryRow(ctx, q.getUserByIDStmt, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, first_name, last_name, is_active, is_verified, created_at, updated_at FROM users
WHERE username = $1 
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.queryRow(ctx, q.getUserByUsernameStmt, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccountBalance = `-- name: UpdateAccountBalance :one
UPDATE accounts
SET balance = $2,
    available_balance = $3,
    locked_balance = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, account_type, balance, available_balance, locked_balance, currency, is_active, created_at, updated_at, currency_id
`

type UpdateAccountBalanceParams struct {
	ID               uuid.UUID      `json:"id"`
	Balance          sql.NullString `json:"balance"`
	AvailableBalance sql.NullString `json:"available_balance"`
	LockedBalance    sql.NullString `json:"locked_balance"`
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error) {
	row := q.queryRow(ctx, q.updateAccountBalanceStmt, updateAccountBalance,
		arg.ID,
		arg.Balance,
		arg.AvailableBalance,
		arg.LockedBalance,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountType,
		&i.Balance,
		&i.AvailableBalance,
		&i.LockedBalance,
		&i.Currency,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CurrencyID,
	)
	return i, err
}

const updateTransactionStatus = `-- name: UpdateTransactionStatus :one
UPDATE transactions
SET status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, account_id, transaction_type, amount, currency, balance_before, balance_after, status, reference_id, reference_type, description, created_at
`

type UpdateTransactionStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (Transaction, error) {
	row := q.queryRow(ctx, q.updateTransactionStatusStmt, updateTransactionStatus, arg.ID, arg.Status)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TransactionType,
		&i.Amount,
		&i.Currency,
		&i.BalanceBefore,
		&i.BalanceAfter,
		&i.Status,
		&i.ReferenceID,
		&i.ReferenceType,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserVerification = `-- name: UpdateUserVerification :one
UPDATE users
SET is_verified = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, username, email, password_hash, first_name, last_name, is_active, is_verified, created_at, updated_at
`

type UpdateUserVerificationParams struct {
	ID         uuid.UUID    `json:"id"`
	IsVerified sql.NullBool `json:"is_verified"`
}

func (q *Queries) UpdateUserVerification(ctx context.Context, arg UpdateUserVerificationParams) (User, error) {
	row := q.queryRow(ctx, q.updateUserVerificationStmt, updateUserVerification, arg.ID, arg.IsVerified)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
