// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateDeposit(ctx context.Context, arg CreateDepositParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetAccountByUserAndType(ctx context.Context, arg GetAccountByUserAndTypeParams) (Account, error)
	GetAccountsByUserID(ctx context.Context, userID uuid.UUID) ([]Account, error)
	GetTransactionByID(ctx context.Context, id uuid.UUID) (Transaction, error)
	GetTransactionsByAccountID(ctx context.Context, arg GetTransactionsByAccountIDParams) ([]Transaction, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error)
	UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (Transaction, error)
	UpdateUserVerification(ctx context.Context, arg UpdateUserVerificationParams) (User, error)
}

var _ Querier = (*Queries)(nil)
